apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  namespace: my-api-{{ .Values.appEnvironment}}
  labels:
    app: my-api-label
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-api-label
  template:
    metadata:
      labels:
        app: my-api-label
    spec:
      containers:
        - name: nodejs-api-container
          image: my-api:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: {{ .Values.appEnvironment }}
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-api-secret
                  key: appsecret